export const getId = state => state.profileData.id;
export const getName = state => state.profileData.name;
export const getStatus = state => state.profileData.status;
export const getDOB = state => state.profileData.DOB;
export const getLocation = state => state.profileData.location;
export const getLinks = state => state.profileData.links;
export const getAvatar = state => state.profileData.avatar;
export const getSubscribed = state => state.profileData.isSubscribed;
export const getMyId = state => state.profileData.myData.id;